# Basis-Konfiguration für alle Pipeline Jobs
# Gemeinsame Einstellungen für Image, Cache, und Setup

.base-config:
  image: node:22-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .pnpm-store/
  variables:
    PNPM_CACHE_FOLDER: .pnpm-store
  before_script:
    - echo "📦 Setting up environment from project configuration..."
    # Read Node version from .nvmrc
    - export NODE_VERSION=$(cat .nvmrc)
    - echo "📌 Required Node.js version from .nvmrc: $NODE_VERSION"
    - node --version
    # Extract pnpm version from package.json packageManager field
    - export PNPM_VERSION=$(node -e "const pkg=require('./package.json'); const pm=pkg.packageManager||'pnpm@10.15.0'; console.log(pm.split('@')[1])")
    - echo "📌 Required pnpm version from package.json: $PNPM_VERSION"
    # Setup pnpm with exact version
    - corepack enable
    - corepack prepare pnpm@${PNPM_VERSION} --activate
    - pnpm --version
    - pnpm config set store-dir $PNPM_CACHE_FOLDER
    - echo "📦 Installing dependencies with frozen lockfile..."
    - pnpm install --frozen-lockfile
    - echo "✅ Environment setup complete"
